# Generated by Django 5.1.1 on 2024-09-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondaryPhoneNumber',
            field=models.CharField(default='__<function now at 0x00000192BA7A4B80>', max_length=15),
        ),
    ]
