# Generated by Django 5.1.1 on 2024-09-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email_user_secondaryphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='__2024-09-17 19:03:44.137993+00:00', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondaryPhoneNumber',
            field=models.CharField(default='__2024-09-17 19:03:44.137993+00:00', max_length=15),
        ),
    ]
