# Generated by Django 5.1.1 on 2024-09-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_email_alter_user_secondaryphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='__2024-09-17 19:04:53.529170+00:00', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationalId',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondaryPhoneNumber',
            field=models.CharField(default='__2024-09-17 19:04:53.529170+00:00', max_length=15),
        ),
    ]
