# Generated by Django 5.1.1 on 2024-09-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_email_alter_user_nationalid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondaryPhoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
