# Generated by Django 5.1.1 on 2024-09-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_avatar_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='NONE', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondaryPhoneNumber',
            field=models.CharField(default='NONE', max_length=15),
        ),
    ]
