# Generated by Django 5.1.1 on 2024-09-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_phonenumber_user_iccid_alter_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationalId',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='answer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='firstName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='lastName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='nationalId',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='statement',
            field=models.CharField(default='', max_length=50),
        ),
    ]
