# Generated by Django 5.1.1 on 2024-09-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_firstname_remove_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumber', unique=True),
        ),
    ]
