# Generated by Django 5.1.1 on 2024-09-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumber'),
        ),
    ]
