# Generated by Django 5.1.1 on 2024-12-03 18:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='average_transaction',
            field=models.CharField(default='20000', max_length=10000000),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.CharField(default='20000', max_length=100000000),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.CharField(default=datetime.datetime(2024, 12, 3, 18, 40, 20, 121123, tzinfo=datetime.timezone.utc), max_length=100)),
                ('_from', models.CharField(default='', max_length=100)),
                ('to', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
