# Generated by Django 5.1.1 on 2024-12-03 20:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_transactions_time_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.CharField(default=datetime.datetime(2024, 12, 3, 20, 26, 53, 474825, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumber'),
        ),
    ]
