# Generated by Django 5.1.1 on 2024-12-05 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_transactions_time_alter_transactions_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentDevice',
            field=models.CharField(default='', max_length=10000000),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.CharField(default=datetime.datetime(2024, 12, 5, 9, 13, 48, 864317, tzinfo=datetime.timezone.utc), max_length=100),
        ),
    ]
