# Generated by Django 5.1.1 on 2025-01-11 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_currentdevice_alter_transactions_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='incorrectPasswordTrials',
            field=models.CharField(default='4', max_length=4),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.CharField(default=datetime.datetime(2025, 1, 11, 18, 21, 56, 312571, tzinfo=datetime.timezone.utc), max_length=100),
        ),
    ]
